/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    _collection: typeof import('./../components/_collection/index.vue')['default']
    CollectionItem: typeof import('./../components/_collection/CollectionItem.vue')['default']
    Dialog: typeof import('./../components/more-layer/dialog/index.vue')['default']
    DialogFormContainer: typeof import('./../components/more-layer/DialogFormContainer.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FlexButtonGroup: typeof import('./../components/basic-material/FlexButtonGroup.vue')['default']
    FlexCard: typeof import('./../components/card/FlexCard.vue')['default']
    IconBaseline: typeof import('./../components/icons/IconBaseline.vue')['default']
    IconClose: typeof import('./../components/icons/IconClose.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconOutline: typeof import('./../components/icons/IconOutline.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    InfinityScroll: typeof import('./../components/data-display/InfinityScroll.vue')['default']
    LayoutCard: typeof import('./../components/card/LayoutCard.vue')['default']
    LightDialog: typeof import('./../components/more-layer/LightDialog.vue')['default']
    Menu: typeof import('./../components/navigation/menu/index.vue')['default']
    MultiContent: typeof import('./../components/animation/MultiContent.vue')['default']
    MyDialog: typeof import('./../components/more-layer/dialog/MyDialog.vue')['default']
    QuarterSector: typeof import('./../components/icons/QuarterSector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpecialCoppt: typeof import('./../components/form/Input/SpecialCoppt.vue')['default']
    SpicalInput: typeof import('./../components/form/Input/SpicalInput.vue')['default']
  }
}
