// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Search: typeof import('./../components/Input/Search.vue')['default']
    ToDoList: typeof import('./../components/ToDoList.vue')['default']
  }
}

export { }
